# playbook to install nginx and start the service
- name: Install and start nginx
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Ensure nginx is running
      command: systemctl status nginx
      register: result

    - debug:
        var: result.stdout_lines